name: hikeabis_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  dio: ^5.3.3
  email_validator: ^2.1.17
  intl: ^0.18.1
  get: ^4.6.6
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  provider: ^6.0.5
  flutter_colorpicker: ^1.0.3
  file_picker: ^6.0.0
  open_file: ^3.3.2
  envied: ^0.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3

flutter:
  uses-material-design: true

  assets:
    - assets/prau-1.JPG
    - assets/hikeabis_logo.png
    - assets/bg.JPG
    - assets/merbabu_awan.JPG
    - assets/berita.png
    - assets/gunung.png
    - assets/panduan.png
    - assets/persyaratan.png
    - assets/sop.png
    - assets/tiket.png
    - assets/cek_kuota.png
    - assets/slider1.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
